
test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

development:
  adapter: postgresql
  encoding: unicode
  database: caves_development
  pool: 5
  username: dagmara
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: caves_production
  pool: 5
  username: dagmara
  password: 

